#!/usr/bin/env bash
set -euo pipefail

MONITOR_NAME="${1:-}"
MODE="${2:-}"
SCALE="${3:-1}"
CONFIG_DIR="$HOME/.config/hypr/generated"
CONFIG_FILE="$CONFIG_DIR/settings-monitors.conf"

if [[ -z "$MONITOR_NAME" || -z "$MODE" ]]; then
    echo "usage: $0 <monitor-name> <mode> <scale>" >&2
    exit 1
fi

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# Generated by quickshell/settings
monitor=$MONITOR_NAME,$MODE,auto,$SCALE
EOF

if command -v hyprctl >/dev/null 2>&1; then
    hyprctl keyword monitor "$MONITOR_NAME,$MODE,auto,$SCALE" >/dev/null 2>&1 || hyprctl reload >/dev/null 2>&1 || true
fi
