#!/usr/bin/env bash
set -euo pipefail

FOLLOW_MOUSE="${1:-1}"
NATURAL_SCROLL="${2:-no}"
CONFIG_DIR="$HOME/.config/hypr/generated"
CONFIG_FILE="$CONFIG_DIR/settings-input.conf"

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# Generated by quickshell/settings
input {
    follow_mouse=$FOLLOW_MOUSE

    touchpad {
        natural_scroll=$NATURAL_SCROLL
    }
}
EOF

if command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
fi
